### ISSUE TITLE
kind "SparkApplication" is not matching in version "radanalytics.io/v1

### ISSUE THREAD

**Issue by ibnsinha** [radanalyticsio/spark-operator#210] opened 2019-03-18 22:07 UTC
### Description:

I am trying to deploy spark-app using "kubectl apply -f examples/app.yaml" but it throws below error: 
error: unable to recognize "examples/app.yaml": no matches for kind "SparkApplication" in version "radanalytics.io/v1"
#### Steps to reproduce:
kubectl apply -f manifest/operator.yaml (where CRD value = true in manifest/operator.yaml)

kubectl apply -f examples/app.yaml

  1.
  1.

**Comment by Jiri-Kremser** [comment] 2019-03-19 12:25
Thanks for reporting the issue!

You've probably hit an issue caused by our recent [change](https://github.com/radanalyticsio/spark-operator/commit/843e93240c41d6e68d5d92487cc54d43ba98e0fb) where we changed:
 `sparkapplication` -> `SparkApplication` and
 `sparkcluster` -> `SparkCluster`

So either make sure, you are using the latest version by explicitly using the image `quay.io/radanalyticsio/spark-operator:0.3.5` in the `operator.yaml` or change the 

`imagePullPolicy: IfNotPresent` -> `imagePullPolicy: Always`
in case you are using the `quay.io/radanalyticsio/spark-operator:latest-released` image

**Comment by ibnsinha** [comment] 2019-03-19 18:54
Thanks for your prompt response. The above steps didn't work. Below are the logs:


$ kubectl get crd
NAME                                              CREATED AT
scheduledscalers.scaling.k8s.restdev.com          2019-03-04T20:51:22Z
scheduledsparkapplications.sparkoperator.k8s.io   2019-03-12T08:18:21Z
sparkapplications.sparkoperator.k8s.io            2019-03-12T08:18:16Z
sparkclusters.radanalytics.io                     2019-03-18T06:28:40Z
$ kubectl get SparkApplications
No resources found.


$ kubectl logs -f `kubectl get pod -l app.kubernetes.io/name=spark-operator -o='jsonpath="{.items[0].metadata.name}"' | sed 's/"//g'`
2019-03-19 18:29:51 INFO  Entrypoint:56 - Starting..
2019-03-19 18:29:52 INFO  Entrypoint:217 - https://10.233.0.1/oapi returned 404. We are not on OpenShift. Assuming, we are on Kubernetes.
2019-03-19 18:29:52 INFO  Manifests:193 - 10 attributes loaded from 1 stream(s) in 2ms, 10 saved, 0 ignored: ["Build-Jdk", "Built-By", "Created-By", "Implementation-Build", "Implementation-Title", "Implementation-URL", "Implementation-Vendor-Id", "Implementation-Version", "Main-Class", "Manifest-Version"]
2019-03-19 18:29:52 INFO  Entrypoint:236 -
Operator has started in version 0.3.5.

2019-03-19 18:29:52 INFO  Entrypoint:239 - Git sha: 3e4488c8
2019-03-19 18:29:52 INFO  Entrypoint:241 - ==================

2019-03-19 18:29:52 INFO  Entrypoint:76 - Kubernetes environment detected.
2019-03-19 18:29:56 INFO  AbstractOperator:242 - Starting 'SparkCluster' operator for namespace spark-operator2
2019-03-19 18:29:57 WARN  VersionUsageUtils:55 - The client is using resource type 'customresourcedefinitions' with unstable version 'v1beta1'
2019-03-19 18:29:57 INFO  AbstractOperator:42 - SparkCluster operator default spark image = quay.io/jkremser/openshift-spark:2.4.0
2019-03-19 18:29:57 INFO  Entrypoint:174 - full reconciliation for 'SparkCluster' operator scheduled (periodically each 180 seconds)
2019-03-19 18:29:57 INFO  Entrypoint:175 - the first full reconciliation for 'SparkCluster' operator is happening in 2 seconds
2019-03-19 18:29:57 INFO  AbstractOperator:242 - Starting 'SparkApplication' operator for namespace spark-operator2
2019-03-19 18:29:57 INFO  Entrypoint:174 - full reconciliation for 'SparkApplication' operator scheduled (periodically each 180 seconds)
2019-03-19 18:29:57 INFO  Entrypoint:175 - the first full reconciliation for 'SparkApplication' operator is happening in 3 seconds
2019-03-19 18:29:57 INFO  AbstractOperator:254 - 'SparkCluster' operator running for namespace spark-operator2
2019-03-19 18:29:57 INFO  Entrypoint:154 - 'SparkCluster' operator started in namespace spark-operator2
2019-03-19 18:29:57 INFO  AbstractWatcher:157 - CustomResource watcher running for kinds SparkCluster
2019-03-19 18:29:57 INFO  AbstractOperator:254 - 'SparkApplication' operator running for namespace spark-operator2
2019-03-19 18:29:57 INFO  Entrypoint:154 - 'SparkApplication' operator started in namespace spark-operator2
2019-03-19 18:29:57 INFO  AbstractWatcher:157 - CustomResource watcher running for kinds SparkApplication
2019-03-19 18:29:59 INFO  AbstractOperator:96 - Running full reconciliation for namespace spark-operator2 and kind SparkCluster..
2019-03-19 18:30:00 INFO  AbstractOperator:113 - toBeDeleted: [my-spark-cluster]
2019-03-19 18:30:00 INFO  AbstractOperator:127 - deleting cluster my-spark-cluster
2019-03-19 18:32:59 INFO  AbstractWatcher:131 - Custom resource in namespace spark-operator2 was ADDED
CR:

2019-03-19 18:32:59 INFO  AbstractWatcher:188 - creating SparkCluster:
my-spark-cluster

2019-03-19 18:32:59 INFO  AbstractWatcher:190 - SparkCluster my-spark-cluster has been  created
2019-03-19 18:32:59 INFO  AbstractOperator:96 - Running full reconciliation for namespace spark-operator2 and kind SparkCluster..
2019-03-19 18:32:59 INFO  AbstractOperator:166 - no change was detected during the reconciliation
Mar 19, 2019 6:34:52 PM okhttp3.internal.platform.Platform log
WARNING: A connection to https://10.233.0.1/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
2019-03-19 18:35:59 INFO  AbstractOperator:96 - Running full reconciliation for namespace spark-operator2 and kind SparkCluster..
2019-03-19 18:35:59 INFO  AbstractOperator:166 - no change was detected during the reconciliation
2019-03-19 18:38:59 INFO  AbstractOperator:96 - Running full reconciliation for namespace spark-operator2 and kind SparkCluster..

**Comment by elmiko** [comment] 2019-03-19 19:06
> $ kubectl get crd
> NAME CREATED AT
> scheduledscalers.scaling.k8s.restdev.com 2019-03-04T20:51:22Z
> scheduledsparkapplications.sparkoperator.k8s.io 2019-03-12T08:18:21Z
> sparkapplications.sparkoperator.k8s.io 2019-03-12T08:18:16Z
> sparkclusters.radanalytics.io 2019-03-18T06:28:40Z
> $ kubectl get SparkApplications
> No resources found.

these logs look like the custom resource for `SparkApplication` does exist in your kubernetes. also the logs do not show an error with the spark operator.

is it possible you are logged in to a different account or cluster?

also, you mention not running openshift, what kubernetes distro are you running?

**Comment by ibnsinha** [comment] 2019-03-19 22:04
I am not running openshift. I build k8s cluster on aws ec2 instances using kubespray.  

I logged into the same cluster where I have spark-operator installed:

$ kubectl get pods
NAME                              READY   STATUS    RESTARTS   AGE
spark-operator-674cf56768-9kgsb   1/1     Running   0          1h

**Comment by elmiko** [comment] 2019-03-19 22:59
ok, so looking at the output again

```
$ kubectl get crd
NAME CREATED AT
scheduledscalers.scaling.k8s.restdev.com 2019-03-04T20:51:22Z
scheduledsparkapplications.sparkoperator.k8s.io 2019-03-12T08:18:21Z
sparkapplications.sparkoperator.k8s.io 2019-03-12T08:18:16Z
sparkclusters.radanalytics.io 2019-03-18T06:28:40Z
```

it would appear that the radanalytics SparkCluster is there but i don't see SparkApplication.

what happens if you run

```
kubectl describe crd sparkapplications.radanalytics.io
```

i'm not sure why you would only have one installed.

**Comment by ibnsinha** [comment] 2019-03-19 23:21
$ kubectl describe crd sparkapplications.radanalytics.io
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "sparkapplications.radanalytics.io" not found

**Comment by elmiko** [comment] 2019-03-19 23:54
it certainly seems like the spark operator is not installing the custom resource definition for some reason.

what does this show

```
kubectl describe crd sparkclusters.radanalytics.io
```

**Comment by Jiri-Kremser** [comment] 2019-03-20 12:13
This looks like a clash of the CRDs, even though, they have different `apiVersion` (`radanalytics.io` vs `sparkoperator.k8s.io`). When the operator starts it tries to create those CRDs if it can't find them.

I've just tried to install both operators and I can see the same result as you

```
λ oc get crd
NAME                                              AGE
scheduledsparkapplications.sparkoperator.k8s.io   1m
sparkapplications.sparkoperator.k8s.io            1m
sparkclusters.radanalytics.io                     20s
```

**Comment by Jiri-Kremser** [comment] 2019-03-20 12:45
https://github.com/jvm-operators/abstract-operator/issues/37

**Comment by Jiri-Kremser** [comment] 2019-03-20 15:42
fixed by 
* https://github.com/jvm-operators/abstract-operator/pull/38
* https://github.com/radanalyticsio/spark-operator/pull/212

the fix will land there in the next release or in the `:latest` image. Thanks @ibnsinha for reporting the issue.

**Closed by Jiri-Kremser** 2019-03-20 15:42 UTC
Labels: bug

**Comment by ibnsinha** [comment] 2019-03-20 18:40
Thanks Jiri-Kremser. I am able to run spark application now :)
