### ISSUE TITLE
Problems installing the operator in CRD version

### ISSUE THREAD

**Issue by stieler-it** [radanalyticsio/spark-operator#187] opened 2019-02-12 12:20 UTC
### Describe the problem:

Installing spark operator worked, however the CRD version fails to start.

#### Steps to reproduce:

  1. kubectl apply -f manifest/operator-crd.yaml
  
#### Observed Results:

Controller fails to start and prints the following error:

```
2019-02-12 11:48:21 WARN VersionUsageUtils:55 - The client is using resource type 'customresourcedefinitions' with unstable version 'v1beta1'
12.2.2019 12:48:21 Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.43.0.1/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:default:spark-operator" cannot list customresourcedefinitions.apiextensions.k8s.io at the cluster scope.
12.2.2019 12:48:21 at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:478)
...
12.2.2019 12:48:21 at io.radanalytics.operator.common.crd.CrdDeployer.initCrds(CrdDeployer.java:31)
```
  
#### Expected Results:

  * Controller starts

#### Additional info

Question: It looks wrong that the namespace `myproject` is referenced here:
https://github.com/radanalyticsio/spark-operator/blob/master/manifest/operator-crd.yaml#L19
Maybe it is related? I used namespace `default` in my tests.

**Comment by elmiko** [comment] 2019-02-12 14:12
hi, i would try adjusting the namespace for the service account to the namespace you are using, or confirm that the created service account can manage resources in every project.

the operator uses the service account to create/destroy/manage pods for the spark cluster. at a guess, perhaps the service account is only available in the `myproject` namespace.

hope that helps

**Comment by Jiri-Kremser** [comment] 2019-02-12 16:33
Nice catch! We are running the tests against minikube that has Kubernetes in version v1.9.0. The later versions of minikube can't be run that easily on Travis CI. I was able to reproduce your error with `v1.10.0` and newer. There must have been some breaking change in how RBAC is proceed in K8s. I'll look into this. Thanks for reporting this issue.

here is how the logs should look like: https://travis-ci.org/radanalyticsio/spark-operator/jobs/490617632#L1119

`kubectl auth can-i --as=spark-operator  list customresourcedefinitions.apiextensions.k8s.io` this should be returning yes, but it isn't

**Comment by Jiri-Kremser** [comment] 2019-02-12 23:20
ah, `kubectl auth can-i --as=` doesn't work with service accounts

@stieler-it 
when using the `default` namespace instead of `myproject` it works on Kubernetes, but it's failing on OpenShift if user doesn't switch the namespace to the default ns. It's because OpenShift extends the idea of namespaces into projects and there is always 1 active project/namespace. Unfortunately, the `ClusterRoleBinding` resource requires some namespace in the `subjects.namespace` field, using the default one is probably better than assuming a ns called "myproject".

**Comment by stieler-it** [comment] 2019-02-14 07:02
If OpenShift and Kubernetes require different configuration, would it be helpful to provide two `-crd.yaml` files?

**Comment by Jiri-Kremser** [comment] 2019-02-14 12:29
I wanted to avoid this. There is already a PR fixing this issue. Once the Travis is green, it will be merged. Probably today.

**Closed** 2019-02-15 00:26 UTC
Labels: bug
